name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

# [env.production]
# name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.libcuda.so", custom_domain = true },
#   { pattern = "quey.libcuda.so", custom_domain = true },
#   { pattern = "gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s-gcr.libcuda.so", custom_domain = true },
#   { pattern = "k8s.libcuda.so", custom_domain = true },
#   { pattern = "ghcr.libcuda.so", custom_domain = true },
#   { pattern = "cloudsmith.libcuda.so", custom_domain = true },
# ]

# [env.production.vars]
# MODE = "production"
# TARGET_UPSTREAM = ""

# [env.staging]
# name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.hostscc.top", custom_domain = true },
  { pattern = "quey.hostscc.top", custom_domain = true },
  { pattern = "gcr.hostscc.top", custom_domain = true },
  { pattern = "k8s-gcr.hostscc.top", custom_domain = true },
  { pattern = "k8s.hostscc.top", custom_domain = true },
  { pattern = "ghcr.hostscc.top", custom_domain = true },
  { pattern = "cloudsmith.hostscc.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.hostscc.top", custom_domain = true }


[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
