name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "rushb.us.kg"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "rushb.us.kg"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.rushb.us.kg", custom_domain = true },
  { pattern = "quay.rushb.us.kg", custom_domain = true },
  { pattern = "gcr.rushb.us.kg", custom_domain = true },
  { pattern = "k8s-gcr.rushb.us.kg", custom_domain = true },
  { pattern = "k8s.rushb.us.kg", custom_domain = true },
  { pattern = "ghcr.rushb.us.kg", custom_domain = true },
  { pattern = "cloudsmith.rushb.us.kg", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
